# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('date_of_birth', models.DateField()),
                ('joined_on', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=256)),
                ('employed_since', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('date_of_birth', models.DateField()),
                ('joined_on', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=256)),
                ('employed_since', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('date_of_birth', models.DateField()),
                ('joined_on', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=256)),
                ('employed_since', models.DateField()),
                ('designation', models.CharField(choices=[(0, 'PROJECT'), (1, 'SENIOR'), (2, 'EXECUTIVE')], max_length=3)),
                ('reports_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Manager')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('incharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Manager')),
            ],
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('date_of_birth', models.DateField()),
                ('joined_on', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=256)),
                ('employed_since', models.DateField()),
                ('automation', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='developer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Team'),
        ),
        migrations.AddField(
            model_name='designer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Team'),
        ),
    ]
