# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='designation',
            field=models.IntegerField(choices=[(0, 'PROJECT'), (1, 'SENIOR'), (2, 'EXECUTIVE')]),
        ),
        migrations.AlterField(
            model_name='manager',
            name='reports_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Manager'),
        ),
    ]
