# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170414_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Manager'),
        ),
    ]
