# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170415_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('date_of_birth', models.DateField()),
                ('joined_on', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=256)),
                ('employed_since', models.DateField()),
                ('designation', models.IntegerField(choices=[(0, 'PROJECT'), (1, 'SENIOR')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='projectmanager',
            name='designation',
            field=models.IntegerField(choices=[(0, 'PROJECT'), (1, 'SENIOR')]),
        ),
        migrations.AlterField(
            model_name='projectmanager',
            name='reports_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Executive'),
        ),
    ]
