# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170415_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='picture',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='developer',
            name='picture',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='executive',
            name='picture',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='picture',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='tester',
            name='picture',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
