# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 06:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_auto_20170416_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='designer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='designer',
            name='joined_on',
        ),
        migrations.RemoveField(
            model_name='designer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='joined_on',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='executive',
            name='email',
        ),
        migrations.RemoveField(
            model_name='executive',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='executive',
            name='joined_on',
        ),
        migrations.RemoveField(
            model_name='executive',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='projectmanager',
            name='email',
        ),
        migrations.RemoveField(
            model_name='projectmanager',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='projectmanager',
            name='joined_on',
        ),
        migrations.RemoveField(
            model_name='projectmanager',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='tester',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tester',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tester',
            name='joined_on',
        ),
        migrations.RemoveField(
            model_name='tester',
            name='last_name',
        ),
        migrations.AddField(
            model_name='designer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='developer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='executive',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tester',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
